name =input("What is your name:")
age =input("How old are you:")
UID=input("What is your UID:")
marks=input("Enter your marks:")
print("Good Morning,",name)
print("Tomar boyosh ",age,"kobe hoilo?")
print("You are Tajbir right?")
print("I know your marks ,you got :",marks)
